using System;
using System.Text;
using NBitcoin;
using WalletWasabi.Crypto;
using Xunit;

namespace WalletWasabi.Tests.UnitTests.Hwi;

/// <summary>
/// Cross-implementation check: SLIP-19 ownership proofs generated by the Krux firmware branch
/// (PMK/krux feat/slip-19-coinjoin, vendored embit, mnemonic "abandon...about", receive path .../1/0)
/// must pass Wasabi's own verifier — the exact check the coordinator runs at input registration.
/// Vectors emitted by krux tests/test_wasabi_vectors.py.
/// </summary>
public class KruxProofCrossCheckTests
{
	private static readonly byte[] Commitment = Encoding.ASCII.GetBytes("krux-wasabi-crosscheck");

	[Theory]
	[InlineData(
		"534c00190101dc798b0eef7ead2c66cf276f1428cb2d92afee7b8e646d3db69cd697619aec4b000247304402203997ce466504bf445145dd21c182ba3208dcda313ebeb94776690abc45446810022001857685c195e252b7c13e2715861ea5e412bd78ec4d661d1e20f6efa6a9f2ef012103025324888e429ab8e3dbaf1f7802648b9cd01e9b418485c5fa4c1b9b5700e1a6",
		"00143e34985dca6fddc9fb369940e4c7d8e2873f529c")]
	[InlineData(
		"534c001901013696d224d96b25b231a2d7ddae1dbc054091bb553b5a00803574b53b5e8439ab00014031102388822bb23f5011d73545fba1574d077833e72b73f7a8c4fd3b4e7d902e4b18f96c600cf0b0712002137695456735b21b8d0750bb6fac7034cc708dda06",
		"5120882d74e5d0572d5a816cef0041a96b6c1de832f6f9676d9605c44d5e9a97d3dc")]
	public void KruxProofPassesWasabiVerifier(string wireHex, string spkHex)
	{
		var proof = OwnershipProof.FromBytes(Convert.FromHexString(wireHex));
		var spk = new Script(Convert.FromHexString(spkHex));
		Assert.True(proof.VerifyOwnership(spk, Commitment, requireUserConfirmation: true));
	}
}
